### ISSUE TITLE
Error starting up the launcher when using Kotlin

### ISSUE THREAD

**Issue by namuan** [shannah/jdeploy-javafx-starter#1]
Hi, 
Thanks for the starter project. 
I tried integrating it in one of the projects that I'm building in Kotlin with JavaFX. 
Everything works fine until it gets to starting up the final application from the `~/Applications` directory and it failed due to the following exception

```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at com.github.namuan.gptfx.MainApp.start(MainApp.kt)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
2022/12/21 10:37:21 Failed to execute Java for package gpt-fx version 0.0.0-main%!(EXTRA *errors.errorString=Java virtual machine exited with code 1)
Finished call to native%
```

My project is over at `https://github.com/namuan/gpt-fx` and the changes are in this branch

```
https://github.com/namuan/gpt-fx/tree/jdeploy-github
```

Please let me know if I'm missing anything 
Thanks

**Comment by shannah** [comment]
The maven build is having dependency issues.  I cloned your branch and I get the same error when I try to run `java -jar target/gpt-fx-1.0-SNAPSHOT.jar`

If you can get that command working, then the resulting jDeploy app will work.

**Comment by shannah** [comment]
I've found the issue.  There was a configuration problem with the maven-jar-plugin.  I've updated the jdeploy-javafx-starter to version 1.0.7 on maven central (will take a few minutes to a few hours usually to be available).

You can then change the version in your pom.xml file to 1.0.7.  I.e.:

```xml
<parent>
        <artifactId>jdeploy-javafx-starter</artifactId>
        <groupId>ca.weblite</groupId>
        <version>1.0.7</version>
    </parent>
```

One other small thing I noticed:

You don't need to include the javafx dependencies in your pom.xml because they are included in the parent pom (in in the jdeploy-javafx-starter pom) - and you are including a different version (17 in yours vs 19 in the parent).
2. You don't need the
